dist: trusty
sudo: required
language: bash

addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'

install:
  - sudo apt-get install ansible -y

script:
  - pwd
  - ls -al eRadical/ansible-my-fedora-workstation/
  - ansible-playbook --syntax-check configure-fedora.yml
