dist: trusty
sudo: required
language: bash

addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'

install:
  - sudo apt-get install ansible -y
  - sudo pip install -U ansible

script:
  - pwd
  - ansible-playbook --syntax-check -i inventory/ configure-fedora.yml
