---
- hosts: localhost
  tasks:

    - name: Install RPM Fusion repos
      dnf:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - ack
        - aspell
        - aspell-en
        - astronomy-backgrounds
        - awscli
        - bmon
        - conky
        - desktop-backgrounds-basic
        - desktop-backgrounds-compat
        - desktop-backgrounds-gnome
        - docker
        - earth-and-moon-backgrounds
        - earth-and-moon-backgrounds-common
        - earth-and-moon-backgrounds-dual
        - "f{{ ansible_distribution_major_version }}-backgrounds"
        - "f{{ ansible_distribution_major_version }}-backgrounds-animated"
        - "f{{ ansible_distribution_major_version }}-backgrounds-base"
        - "f{{ ansible_distribution_major_version }}-backgrounds-extras-base"
        - "f{{ ansible_distribution_major_version }}-backgrounds-extras-gnome"
        - "f{{ ansible_distribution_major_version }}-backgrounds-gnome"
        - fedora-workstation-backgrounds
        - ffmpeg
        - fuse-sshfs
        - gedit-plugin-bookmarks
        - gedit-plugin-bracketcompletion
        - gedit-plugin-charmap
        - gedit-plugin-codecomment
        - gedit-plugin-colorpicker
        - gedit-plugin-colorschemer
        - gedit-plugin-commander
        - gedit-plugin-dashboard
        - gedit-plugin-drawspaces
        - gedit-plugin-findinfiles
        - gedit-plugin-git
        - gedit-plugin-joinlines
        - gedit-plugin-multiedit
        - gedit-plugins
        - gedit-plugins-data
        - gedit-plugin-smartspaces
        - gedit-plugin-synctex
        - gedit-plugin-terminal
        - gedit-plugin-textsize
        - gedit-plugin-wordcompletion
        - gedit-plugin-zeitgeist
        - glances
        - gnome-backgrounds
        - gnome-backgrounds-extras
        - gnome-music
        - gnome-shell-extension-background-logo
        - gnome-shell-extension-calc
        - gnome-shell-extension-gpaste
        - gnome-shell-extension-openweather
        - gnome-tweak-tool
        - golang
        - golang-bin
        - golang-src
        - google-authenticator
        - gwenview
        - htop
        - iftop
        - iotop
        - iptraf-ng
        - kernel-devel
        - kernel-modules-extra
        - libreoffice-gallery-vrt-network-equipment
        - libreoffice
        - libreoffice-langpack-en
        - libreoffice-langpack-ro
        - libreoffice-wiki-publisher
        - lm_sensors
        - lokalize
        - lshw
        - lynx
        - mc
        - mediawriter
        - meld
        - 'mplayer*'
        - nautilus-open-terminal
        - nload
        - nmon
        - ntop
        - ntp
        - numad
        - numlockx
        - perf
        - php
        - php-cli
        - poedit
        - powertop
        - pulseaudio-equalizer
        - rkhunter
        - s3cmd
        - strace
        - synergy
        - system-config-printer
        - tigervnc
        - tuned
        - vim-common
        - vim-enhanced
        - vim-filesystem
        - 'vlc*'
        - 'wine*'
        - wireshark-gnome
        - xorg-x11-server-Xvfb
    - name: Remove some packages
      dnf:
        name: "{{ item }}"
        state: absent
      become: true
      with_items:
        - evolution
        - fprintd

    - name: For groupinstall require at least Ansible 2.3.2.0
      fail:
        msg: "This playbook requires Ansible 2.3.2.0 or greater."
      when: ansible_version.full|version_compare('2.3.2.0', '<')

    - name: Install groups of packages
      dnf:
        name: "@{{ item }}"
        state: present
      become: true
      with_items:
        - c-development
        - development-tools

    - name: Start usefull services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      become: true
      with_items:
        - numad
        - tuned
        - ntpd

    - name: Stop unusefull services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
        masked: yes
      become: true
      with_items:
        - iio-sensor-proxy
