---
- name: Enable router advertisements
  sysctl:
    name: "net.ipv6.conf.{{ item }}.accept_ra"
    value: 1
    state: present
    ignoreerrors: yes
  with_items: "{{ ansible_interfaces }} + ['all']"

- name: Disable DAD (Duplicate Address Detection)
  sysctl:
    name: "net.ipv6.conf.{{ item }}.accept_dad"
    value: 0
    state: present
    ignoreerrors: yes
  with_items: "{{ ansible_interfaces }} + ['all']"

- name: Disable DUID
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    line: "send dhcp-client-identifier = hardware;"
    owner: root
    group: root
    mode: 0644
  when: dhcp_disable_duid|bool == True
