---
- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ install_packages }}"

- name: Remove some packages
  dnf:
    name: "{{ item }}"
    state: absent
  become: true
  with_items: "{{ remove_packages }}"

- name: Install Slack
  dnf:
    name: slack
    state: latest
  become: true
  when: workstation_slack|bool == True
