---
- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ install_packages }}"

- name: Remove some packages
  dnf:
    name: "{{ item }}"
    state: absent
  become: true
  with_items: "{{ remove_packages }}"

- name: Remove Evolution
  dnf:
    name: evolution
    state: absent
  become: true
  when: remove_evolution|bool == True
