---
- name: Install RPM Fusion repos
  dnf:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install Slack repo
  yum_repository:
    name: slack
    description: slack
    baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64
    enabled: yes
    gpgcheck: no
    gpgkey: https://packagecloud.io/gpg.key
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
  when: workstation_slack|bool == True
