---
- name: Install packages
  dnf:
    name:
      - python-dopy
    state: latest
  become: true

- name: Try to install doctl, but don't fail the whole thing
  command: go get -u github.com/digitalocean/doctl/cmd/doctl
  ignore_errors: yes
