---
- name: Install packages
  dnf:
    name: "{{ install_packages }}"
    state: latest
  become: true

- name: Install groups of packages
  dnf:
    name:
      - "@c-development"
      - "@development-tools"
    state: present
  become: true
  when: ansible_version.full is version_compare('2.3.2.0', '>=')

- name: Install PyCharm
  dnf:
    name:
      - pycharm-community
      - pycharm-community-plugins
    state: latest
  become: true
  when: dev_pycharm|bool == True

- name: Install Atom
  dnf:
    name: "https://github.com/atom/atom/releases/download/v{{ dev_atom_version }}/atom.x86_64.rpm"
    state: present
  become: true
  when: dev_atom|bool == True

- name: Install NodeJS
  dnf:
    name: nodejs
    state: present
  become: true
  when: nodejs_install|bool == True
