- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ install_packages }}"

- name: Install groups of packages
  dnf:
    name: "@{{ item }}"
    state: present
  become: true
  with_items:
    - c-development
    - development-tools
  when: ansible_version.full|version_compare('2.3.2.0', '>=')
