- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ install_packages }}"

- name: Install groups of packages
  dnf:
    name: "@{{ item }}"
    state: present
  become: true
  with_items:
    - c-development
    - development-tools
  when: ansible_version.full|version_compare('2.3.2.0', '>=')

- name: Install PyCharm
  dnf:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
  - pycharm-community
  - pycharm-community-plugins
  when: dev_pycharm|bool == True

- name: Install Atom
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
  - "https://github.com/atom/atom/releases/download/v{{ dev_atom_version }}/atom.x86_64.rpm"
  when: dev_atom|bool == True

- name: Install NodeJS
  dnf:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
  - nodejs
  when: nodejs_install|bool == True
