---
- name: Sanity check
  fail:
    msg: "From Fedora repos you can only get PHP 7.2. From Remi repos you can get PHP 7.2 or 7.3."
  when: php_source == "os" and php_version != "7.2"

- name: Install REMI and activate it
  block:
  - name: Install REMI repo
    dnf:
      name:
        - http://rpms.remirepo.net/fedora/remi-release-29.rpm
      state: present
  - name: Aactivate it
    command: "dnf module install remi-php:{{ php_version }}"
    args:
      warn: false
  when: php_source == "remi"

- name: Install PHP packages
  become: true
  dnf:
    name:
      - php
      - php-cli
    state: present
