---
- name: Download PhpStorm {{ dev_phpstorm_version }}
  become: true
  get_url:
    url: "http://download.jetbrains.com/webide/PhpStorm-{{ dev_phpstorm_version }}.tar.gz"
    dest: "/opt/PhpStorm-{{ dev_phpstorm_version }}.tar.gz"
    mode: 0440

- name: Unarchive PhpStorm
  become: true
  unarchive:
    src: "/opt/PhpStorm-{{ dev_phpstorm_version }}.tar.gz"
    dest: /opt

- name: Symlink build to a fixed folder
  become: true
  file:
    src: "/opt/PhpStorm-{{ dev_phpstorm_build }}"
    dest: "/opt/PhpStorm"
    state: link
    force: yes

- name: Put the correct .desktop file
  template:
    src: jetbrains-phpstorm.desktop.j2
    dest: /usr/local/share/applications/jetbrains-phpstorm.desktop
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
