---
- name: Download PyCharm {{ dev_pycharm_version }}
  become: true
  get_url:
    url: "https://download-cf.jetbrains.com/python/pycharm-community-{{ dev_pycharm_version }}.tar.gz"
    dest: "/opt/pycharm-community-{{ dev_pycharm_version }}.tar.gz"
    mode: 0666

- name: Unarchive PyCharm
  become: true
  unarchive:
    src: "/opt/pycharm-community-{{ dev_pycharm_version }}.tar.gz"
    dest: /opt

- name: Symlink build to a fixed folder for PyCharm {{ dev_pycharm_version }}
  become: true
  file:
    src: "/opt/pycharm-community-{{ dev_pycharm_build }}"
    dest: "/opt/pycharm-community"
    state: link
    force: yes

- name: Put the correct .desktop file
  become: true
  template:
    src: jetbrains-pycharm-community.desktop.j2
    dest: /usr/local/share/applications/jetbrains-pycharm-community.desktop
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
